// Mock data for static builds when DATABASE_URL is not available
export const mockProducts = [
  {
    id: "1",
    sku: "FM-BO-001",
    slug: "blue-oyster",
    name: "Blue Oyster Mushrooms",
    summary: "Delicate, mild flavor with a velvety texture. Perfect for stir-fries and pasta dishes.",
    detailsMd: null,
    categoryId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "1",
      slug: "fresh",
      name: "Fresh Mushrooms",
      description: "Premium fresh mushrooms",
      colorHex: "#3b82f6",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    variants: [
      {
        id: "1",
        productId: "1",
        name: "8 oz",
        priceCents: 1200,
        unit: "oz",
        stock: 10,
        isActive: true,
      },
    ],
  },
  {
    id: "2",
    sku: "FM-LM-001",
    slug: "lions-mane",
    name: "Lion's Mane Mushrooms",
    summary: "Seafood-like texture with a subtle, sweet flavor. Known for cognitive benefits.",
    detailsMd: null,
    categoryId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "1",
      slug: "fresh",
      name: "Fresh Mushrooms",
      description: "Premium fresh mushrooms",
      colorHex: "#3b82f6",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    variants: [
      {
        id: "2",
        productId: "2",
        name: "8 oz",
        priceCents: 1500,
        unit: "oz",
        stock: 8,
        isActive: true,
      },
    ],
  },
  {
    id: "3",
    sku: "FM-PO-001",
    slug: "pink-oyster",
    name: "Pink Oyster Mushrooms",
    summary: "Beautiful pink color with a mild, woody flavor. Great for visual appeal.",
    detailsMd: null,
    categoryId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "1",
      slug: "fresh",
      name: "Fresh Mushrooms",
      description: "Premium fresh mushrooms",
      colorHex: "#3b82f6",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    variants: [
      {
        id: "3",
        productId: "3",
        name: "8 oz",
        priceCents: 1300,
        unit: "oz",
        stock: 12,
        isActive: true,
      },
    ],
  },
  {
    id: "4",
    sku: "GK-BO-001",
    slug: "blue-oyster-kit",
    name: "Blue Oyster Grow Kit",
    summary: "Complete grow kit with everything you need to grow blue oyster mushrooms at home.",
    detailsMd: null,
    categoryId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "2",
      slug: "grow-kits",
      name: "Grow Kits",
      description: "Complete mushroom growing kits",
      colorHex: "#10b981",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    variants: [
      {
        id: "4",
        productId: "4",
        name: "Standard Kit",
        priceCents: 3500,
        unit: "kit",
        stock: 5,
        isActive: true,
      },
    ],
  },
  {
    id: "5",
    sku: "GK-LM-001",
    slug: "lions-mane-kit",
    name: "Lion's Mane Grow Kit",
    summary: "Everything you need to grow lion's mane mushrooms. Easy to use, perfect for beginners.",
    detailsMd: null,
    categoryId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "2",
      slug: "grow-kits",
      name: "Grow Kits",
      description: "Complete mushroom growing kits",
      colorHex: "#10b981",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    variants: [
      {
        id: "5",
        productId: "5",
        name: "Standard Kit",
        priceCents: 4000,
        unit: "kit",
        stock: 3,
        isActive: true,
      },
    ],
  },
  {
    id: "6",
    sku: "GK-PO-001",
    slug: "pink-oyster-kit",
    name: "Pink Oyster Grow Kit",
    summary: "Grow stunning pink oyster mushrooms at home with this all-in-one kit.",
    detailsMd: null,
    categoryId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "2",
      slug: "grow-kits",
      name: "Grow Kits",
      description: "Complete mushroom growing kits",
      colorHex: "#10b981",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    variants: [
      {
        id: "6",
        productId: "6",
        name: "Standard Kit",
        priceCents: 3500,
        unit: "kit",
        stock: 4,
        isActive: true,
      },
    ],
  },
  {
    id: "7",
    sku: "LC-BO-001",
    slug: "blue-oyster-lc",
    name: "Blue Oyster Liquid Culture",
    summary: "High-quality liquid culture for blue oyster mushrooms. Sterile and ready to use.",
    detailsMd: null,
    categoryId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "3",
      slug: "liquid-cultures",
      name: "Liquid Cultures",
      description: "Sterile liquid cultures",
      colorHex: "#8b5cf6",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    variants: [
      {
        id: "7",
        productId: "7",
        name: "10ml Syringe",
        priceCents: 1500,
        unit: "syringe",
        stock: 15,
        isActive: true,
      },
    ],
  },
  {
    id: "8",
    sku: "LC-LM-001",
    slug: "lions-mane-lc",
    name: "Lion's Mane Liquid Culture",
    summary: "Premium liquid culture for lion's mane cultivation. Lab-tested for purity.",
    detailsMd: null,
    categoryId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "3",
      slug: "liquid-cultures",
      name: "Liquid Cultures",
      description: "Sterile liquid cultures",
      colorHex: "#8b5cf6",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    variants: [
      {
        id: "8",
        productId: "8",
        name: "10ml Syringe",
        priceCents: 1800,
        unit: "syringe",
        stock: 10,
        isActive: true,
      },
    ],
  },
  {
    id: "9",
    sku: "LC-PO-001",
    slug: "pink-oyster-lc",
    name: "Pink Oyster Liquid Culture",
    summary: "Vibrant pink oyster liquid culture. Perfect for home cultivators.",
    detailsMd: null,
    categoryId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "3",
      slug: "liquid-cultures",
      name: "Liquid Cultures",
      description: "Sterile liquid cultures",
      colorHex: "#8b5cf6",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    variants: [
      {
        id: "9",
        productId: "9",
        name: "10ml Syringe",
        priceCents: 1500,
        unit: "syringe",
        stock: 12,
        isActive: true,
      },
    ],
  },
];

export function getMockProductsByCategory(categorySlug: string) {
  return mockProducts.filter(p => p.category.slug === categorySlug);
}
